# Generated by Django 4.0 on 2024-05-08 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('login', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('weight', models.FloatField()),
                ('for_menu', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128)),
                ('dishes', models.ManyToManyField(to='restaurant.Dish')),
            ],
        ),
    ]
